Oy2 24270
Enterprise-CMCS/macpro-onemac pull request #1290
Opened 2023-06-23 16:09 UTC by kristin-at-theta

Story: https://qmacbis.atlassian.net/browse/OY2-XXXX
Endpoint: See github-actions bot comment

### Details

A quick summary of the intended outcome of this PR.

### Changes

- Specific functionality changes, or
- A specific bug addressed in this PR

### Implementation Notes

- Developer focused info that may affect future work

### Test Plan

1. Test step 1
2. Test step 2

2023-06-28 03:49 UTC, bflynn-cms requested changes
Style, format, positioning, opening of first history item, hiding if no items all look good.

I did encounter an issue when doing an admin changePackageId funciton though in that I am seeing duplicate records for each action. I was able to duplicate this duplication a few times. I did not yet test any of the other admin actions.

2023-06-29 21:10 UTC, kristin-at-theta commented
the duplicate entries are somewhat purposeful... as we can only make admin changes to events, so changing the PackageID is really changing all the IDs in each event... AND we need to keep it that way because sometimes it is the RAI response ID that gets edited to MATCH it to the original submission... 
In any case, the duplication does Look Weird so I updated the package builder to remove duplicates based on the timestamp... which means the "Admin Changes" are not exactly correct for all the elements of the package, but does roll up the changes and does not confuse the user with duplicates - maybe hopefully??

2023-06-30 13:04 UTC, bflynn-cms approved these changes

2023-06-30 13:05 UTC, bflynn-cms commented
> the duplicate entries are somewhat purposeful... as we can only make admin changes to events, so changing the PackageID is really changing all the IDs in each event... AND we need to keep it that way because sometimes it is the RAI response ID that gets edited to MATCH it to the original submission... In any case, the duplication does Look Weird so I updated the package builder to remove duplicates based on the timestamp... which means the "Admin Changes" are not exactly correct for all the elements of the package, but does roll up the changes and does not confuse the user with duplicates - maybe hopefully??

yeah I see what you mean, I think how you hide the duplicates makes sense. Thanks!

2023-07-05 13:41 UTC, merged