Shorten given list of extensions
Enterprise-CMCS/macpro-onemac pull request #1351
Opened 2023-08-24 17:28 UTC by kevinhaube

Story: https://qmacbis.atlassian.net/browse/OY2-24878

### Details

Adjusts the copy for attachment file types text.

### Changes

- N/A

### Implementation Notes

- N/A

### Test Plan

1. Navigate to the dashboard as a submitting user
2. Use "New Submission" button and triage options to navigate to each form page
3. Ensure each form page shows the proper copy for attachment file types

2023-08-24 18:26 UTC, kevinhaube commented
https://dr7z9fwgoblun.cloudfront.net/

2023-08-25 15:33 UTC, kristin-at-theta approved these changes
Changes look great and follow the AC for the file list.

I clicky-clicky'd through all the forms and they all show the same list (no weird overwriting somewhere) and the FAQ link goes to the correct section.

Approved! -- and then I re-read the AC!  oops :)

2023-08-25 15:35 UTC, kristin-at-theta requested changes
file types should be file formats per the AC

2023-08-25 15:35 UTC, kristin-at-theta commented on services/ui-src/src/libs/formLib.tsx
> +    We accept the following file types: <b>.docx, .jpg, .pdf, .png, .xlsx.</b>{" "}
Though WHOOOPS - missed that the AC says file "formats" not "types" -- probably to keep from being confused with attachment types?!

2023-08-25 17:13 UTC, kristin-at-theta approved these changes
Hooray!

Approved (again)

2023-08-28 16:47 UTC, merged